const en = {
    "lead-title": "Travel in Russia",
    "lead-subtitle": "The real country is not in the news releases, but here.",
    "lead-capton": "YOUR SHELF IS THE UPPER ONE",
    "intro-title": "What didn't we see there?",
    "intro-subtitle": "According to VTsIOM polls, 95% of Russians dream of going somewhere, but only 36% plan to spend a vacation in their native country. Like, what haven't we seen here at home? In fact, Russia is a whole universe with the gentle sea of the south, the dense forests of the Sayan Mountains and the harsh ice of the Putorana plateau. And you can also see all these beauties without millions on your account, a passport and many hours of flights. Like, for example, Vera Bashmakova — a brave young mother who took three children in her arms, sat them in her Lada and drove 20 thousand kilometers across her native country. We have selected and described some interesting places worthy of your vacation.",
    "intro-list-1": "Time zones 11",
    "intro-list-2": "UNESCO Natural Heritage Sites 12",
    "intro-list-3": "UNESCO Cultural Heritage Sites 16",
    "intro-list-4": "Nature reserves 105",
    "intro-list-5": "Airports 241",
    "place-title-kosa": "Curonian Spit",
    "place-paragraph-one-kosa": "Here, in the middle of forests and sand dunes, you can see two water horizons — the calm Curonian Lagoon on one side and the rippling waves of the Baltic Sea on the other. A unique natural area on the edge of the Russian enclave.",
    "place-paragraph-two-kosa": "The Kaliningrad Region does not end there. For the traveler and researcher, there is the westernmost point of Russia, the Baltic Spit, in the same neighborhood, and the German heritage of placers of small seaside towns. The atmosphere of these places eliminates the hustle and bustle, plunging into the tranquility of nature and the smell of the steel, cool sea.",
    "place-title-National-Geographic": "Kolskiy",
    "place-paragraph-one-National-Geographic": "Almost the entire peninsula is located beyond the Arctic Circle. The Sami tundra, from which to the south is the taiga, and to the north is the Arctic Ocean, pretending to be the Barents Sea.",
    "place-paragraph-two-National-Geographic": "You may have watched Zvyagintsev and even heard the story of the Arctic festival in Teriberka. Perhaps the word 'Khibiny' did not remain under the snow of school memories of geography lessons. Perhaps you were not interested in the ultra-deep well penetrating the earth's crust, and apathy has been covering you for a long time. But your dream of seeing the Northern lights begins to come true with a ticket to Murmansk.",
    "place-title-Altai": "Altai",
    "place-paragraph-one-Altai": "Altai is one of the most beautiful places in Russia. First of all, because of the mountains: if you drive along the ridge, you will see slopes strewn with pine trees, mountain rivers and lakes. And if you open the windows in the car, you can get acquainted with the invisible miracle of these places — mountain air.",
    "place-paragraph-two-Altai": "The climate in Altai is temperate, so it's best to go here in summer. So you will see all the diversity of the local flora and fauna. Moose roam the forests of Altai, eagles fly over the ridges, and roe deer graze on the plains. And the famous manuls are also inhabitants of the Altai Territory.",
    "place-title-baikal": "Winter Baikal",
    "place-paragraph-one-baikal": "Everyone knows Baikal as the largest lake in the world. Many also know that this is the largest source of fresh water and one of the most beautiful places in Russia.",
    "place-paragraph-two-baikal": "Of course, this is all true. But Baikal is still an ideal place for skioring competitions. This is a kind of sport when a skier ties himself to a motorcycle, and the tandem tries to develop as much speed as possible on the ice. In March 2019, a world record of 197.011 km/h was set at the Baikal Mile Festival.",
    "place-title-Karelia": "Karelia",
    "place-paragraph-Karelia": "Siberia does not end in the Urals, but in Karelia: Siberian larch, which forms the taiga, does not grow west of the Water Lake. But here it reaches 30 meters — the forests of Karelian national parks have never known an axe because of impassable swamps. Some pines are already more than half a millennium old. Touch a living being who saw the sun before Ivan the Terrible saw it. In the virgin forest, you will not find a trail for a hundred kilometers. And on rare paths, trees a couple of meters from the ground are marked with bear claws. So that everyone knows who is the boss here.",
    "cover-title": "To Baikal by dogs",
    "cover-subtitle": "Based on the educational topic about the Trans—Siberian Railway - a journey from the capital to Lake Baikal by train.",
    "footer-link-maps": "Maps",
    "footer-link-weather": "Weather",
    "footer-link-schedule": "Schedule",
    "footer-link-calendar": "Calendar",
    "footer-link-trip": "Trip",

}

const ru = {
    "lead-title": "Путешествия по России",
    "lead-subtitle": "Настоящая страна не в выпусках новостей, а здесь.",
    "lead-capton": "ВАША ПОЛКА — ВЕРХНЯЯ",
    "intro-title": "Чего мы там не видели?",
    "intro-subtitle": "По опросам ВЦИОМ, 95% россиян мечтают куда-нибудь поехать, но только 36% планируют провести отпуск в родной стране. Мол, чего мы тут, дома, не видели? На самом деле, Россия — это целая вселенная с ласковым морем юга, густыми лесами Саян и суровыми льдами плато Путорана. А ещё увидеть все эти красоты можно без миллионов на счету, загранпаспорта и многочасовых перелетов. Как, например, Вера Башмакова — смелая молодая мама, которая взяла в охапку троих детей, усадила их в свою «Ладу» и проехала 20 тысяч километров по родной стране. Мы выбрали и описали некоторые интересные места, достойные вашего отпуска.",
    "intro-list-1": "Часовых поясов 11",
    "intro-list-2": "Объектов природного наследия ЮНЕСКО 12",
    "intro-list-3": "Объектов культурного наследия ЮНЕСКО 16",
    "intro-list-4": "Природных заповедников 105",
    "intro-list-5": "Аэропортов 241",
    "place-title-kosa": "Куршская коса",
    "place-paragraph-one-kosa": "Здесь, посреди лесов и песчаных дюн, вы сможете увидеть два водных горизонта — спокойного Куршского залива с одной стороны и подёрнутого рябью волн Балтийского моря с другой. Уникальная природная зона на краю российского анклава.",
    "place-paragraph-two-kosa": "На этом Калининградская область не заканчивается. Для путешественника и исследователя там же по соседству — самая западная точка России, Балтийская коса, — и немецкое наследие россыпи небольших приморских городов. Атмосфера здешних мест исключает суету, окуная в спокойствие природы и запах стального, прохладного моря.",
    "place-title-National-Geographic": "Кольский",
    "place-paragraph-one-National-Geographic": "Почти весь полуостров находится за Полярным кругом. Саамская тундра, от которой на юг — тайга, а на север — Ледовитый океан, прикидывающийся Баренцевым морем.",
    "place-paragraph-two-National-Geographic": "Возможно, вы смотрели Звягинцева и даже слышали историю арктического фестиваля в Териберке. Возможно, слово «Хибины» не осталось под снегом школьных воспоминаний об уроках географии. Возможно, вы не интересовались пронизывающей земную кору сверхглубокой скважиной, а от апатитов вас давно накрывает апатия. Но ваша мечта увидеть северное сияние начинает сбываться с билетом в Мурманск.",
    "place-title-Altai": "Алтай",
    "place-paragraph-one-Altai": "Алтай — одно из красивейших мест в России. В первую очередь из-за гор: если ехать вдоль хребта, вы увидите склоны, усыпанные соснами, горные реки и озёра. А если вы откроете в автомобиле окна, сможете познакомиться с невидимым чудом здешних мест — горным воздухом.",
    "place-paragraph-two-Altai": "Климат на Алтае умеренный, поэтому ехать сюда лучше всего летом. Так вы увидите всё разнообразие местной флоры и фауны. По лесам Алтая бродят лоси, над хребтами летают орлы, а на равнинах пасутся косули. И знаменитые манулы — тоже обитатели Алтайского края.",
    "place-title-baikal": "Зимний Байкал",
    "place-paragraph-one-baikal": "Всем известен Байкал как крупнейшее озеро в мире. Многие также знают, что это самый большой источник пресной воды и одно из красивейших мест в России.",
    "place-paragraph-two-baikal": "Конечно, это всё так. Но Байкал ещё идеальное место для соревнований по скийорингу. Это такой вид спорта, когда лыжник привязывает себя к мотоциклу, и тандем старается развить как можно бóльшую скорость на льду. В марте 2019 года на фестивале «Байкальская миля» был поставлен мировой рекорд — 197.011 км/ч.",
    "place-title-Karelia": "Карелия",
    "place-paragraph-Karelia": ">Сибирь заканчивается не на Урале, а в Карелии: образующая тайгу сибирская лиственница не растёт западнее Водлозера. Зато здесь она вымахивает на 30 метров — леса карельских национальных парков из-за непроходимых болот никогда не знали топора. Некоторым соснам уже больше чем полтысячелетия. Прикоснитесь к живому существу, видевшему солнце раньше, чем увидал его Иван Грозный. В девственном лесу на сотню километров не встретишь тропы. А на редких тропинках деревья в паре метров от земли помечены медвежьими когтями. Чтобы все знали, кто тут хозяин.",
    "cover-title": "До Байкала «на&nbsp;собаках»",
    "cover-subtitle": "По мотивам учебной темы о&nbsp;Транссибе&nbsp;—&nbsp;путешествие от&nbsp;столицы&nbsp;до&nbsp;Байкала&nbsp;на электричках.",
    "footer-link-maps": "Карты",
    "footer-link-weather": "Погода",
    "footer-link-schedule": "Расписание",
    "footer-link-calendar": "Календарь",
    "footer-link-trip": "Путешествия",
}